import type { AnalysisReport, CheckResult } from "./types";
import { CATEGORY_LABELS, impactOf } from "./scoring";

const STATUS_MARK: Record<CheckResult["status"], string> = {
  pass: "PASS",
  warn: "WARN",
  fail: "FAIL",
};

/**
 * Render a report as Markdown.
 *
 * Markdown rather than PDF or HTML on purpose: the most common thing to do with
 * this output is paste it into an issue, a doc, or another model's context
 * window, and Markdown is what all three read best.
 */
export function reportToMarkdown(report: AnalysisReport): string {
  const lines: string[] = [];

  lines.push(`# GEO audit: ${report.finalUrl}`);
  lines.push("");
  lines.push(`**Overall score: ${report.overallScore}/100 (grade ${report.grade})**`);
  lines.push("");
  lines.push(`- Analysed: ${new Date(report.fetchedAt).toISOString()}`);
  lines.push(`- HTTP status: ${report.httpStatus}`);
  if (report.requestedUrl !== report.finalUrl) {
    lines.push(`- Requested URL: ${report.requestedUrl} (redirected)`);
  }
  lines.push("");

  lines.push("## Category scores");
  lines.push("");
  lines.push("| Category | Score |");
  lines.push("| --- | --- |");
  for (const category of report.categories) {
    lines.push(`| ${CATEGORY_LABELS[category.category]} | ${category.score}/100 |`);
  }
  lines.push("");

  const actionable = report.checks.filter((check) => check.status !== "pass" && check.weight > 0);
  if (actionable.length > 0) {
    lines.push("## Priority fixes");
    lines.push("");
    lines.push("Ordered by recoverable score (weight × gap).");
    lines.push("");
    for (const [index, check] of actionable.slice(0, 5).entries()) {
      lines.push(`${index + 1}. **${check.label}** (${check.score}/100) — ${check.fix}`);
    }
    lines.push("");
  }

  lines.push("## All checks");
  lines.push("");

  for (const check of report.checks) {
    lines.push(`### ${STATUS_MARK[check.status]} — ${check.label} (${check.score}/100)`);
    lines.push("");
    lines.push(
      `*Category: ${CATEGORY_LABELS[check.category]} · weight ${check.weight} · impact ${Math.round(impactOf(check))}*`,
    );
    lines.push("");
    for (const finding of check.findings) lines.push(`- ${finding}`);
    lines.push("");
    lines.push(`**Fix:** ${check.fix}`);
    lines.push("");
  }

  if (report.llmReview && report.llmReview.suggestions.length > 0) {
    lines.push("## AI rewrite suggestions");
    lines.push("");
    lines.push(`Generated by ${report.llmReview.model}.`);
    lines.push("");
    for (const suggestion of report.llmReview.suggestions) {
      lines.push(`### ${suggestion.title}`);
      lines.push("");
      lines.push(suggestion.rationale);
      lines.push("");
      lines.push("> " + suggestion.rewrite.replace(/\n/g, "\n> "));
      lines.push("");
    }
  }

  lines.push("---");
  lines.push("");
  lines.push("Generated by [Envoyix](https://envoyix.vercel.app).");

  return lines.join("\n");
}
